---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "12/2/2021"

quarter <- "Fall2021"

week_folder <- "12-02_Shakhnarovich"


title <- "Detection and Description of Change in Visual Streams"


speaker <- "Greg Shakhnarovich "
department <- ""
university <- "Toyota Technological Institute"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Fall2021/issues/11"
zoom_url <- "https://uchicago.zoom.us/j/92782114396?pwd=Q3RsR0YvbDFrd2R0MWZ4QllKUUFtZz09"


#Papers

week_paper_ref0 <- "David Gilton, Ruotian Luo, Rebbecca Willett, and Greg Shaknarovich. 2020. 'Detection and Description of Change in Visual Streams.'"
week_paper_file0 <- "https://arxiv.org/pdf/2003.12633.pdf"



#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](",week_paper_file0,")")
  



```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** We will look at the problem of identifying meaningful changes in sequences of images, both as a detection problem (find when the change occurs) and a description problem (describe the nature of the change in natural language). I will discuss our recent work on these problems (joint with Davis Gilton, Ruotian Luo and Rebecca Willett) in which we show that tackling them jointly may be beneficial. 


</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**Greg Shakhnarovich** is a Professor at the Toyota Technological Institute at Chicago, an independent, philanthropically funded graduate research institute on the University of Chicago campus. He also holds a part-time appointment at the CS Department, the University of Chicago. Prior to joining TTIC in 2008, Greg was a postdoctoral scholar at Brown University. He obtained his PhD degree in Electrical Engineering and Computer Science from MIT in 2005. Greg is a recipient of IBM Faculty Award and the Google Faculty Research Award, regularly serves as an Area Chair in flagship vision and learning conferences, and is an Associate Editor of the IEEE Transactions of Pattern Analysis and Machine Intelligence. Greg's research interests lie broadly in computer vision and machine learning. 
</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held in Rm 295 of 1155 East 60th St. MACSS students who have a last name starting with M through Z (Group 2) are required to attend this week's talk in person. All MACSS faculty members are also welcome to join the talk in person. The rest of MACSS students (Group 1) and all other attendees will need to join the meeting via Zoom ([link](`r zoom_url`)).
</p>

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a well-developed group question on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository.</a>

This week's suggested readings:

- `r readings0`


<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:00 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
