---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)

date <- "11/18/2021"

quarter <- "Fall2021"

week_folder <- "11-18_Chetty"


title <- "Only 3 Left At This Price: A Tale of Misleading Online Content and Consumer Protections"


speaker <- "Marshini Chetty"
department <- "Computer Science"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"

#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Fall2021/issues/10"
zoom_url <- "https://uchicago.zoom.us/j/92782114396?pwd=Q3RsR0YvbDFrd2R0MWZ4QllKUUFtZz09"


#Papers
week_paper_ref0 <- "Schaffner, B., Lingareddy, N., & Chetty, M. Understanding Account Deletion and Related Dark Patterns on Social Media. Working Paper."
week_paper_file0 <- "Working_Paper_Schaffner_CSCW.pdf"

week_paper_ref1 <- "Mathur, A., Acar, G., Friedman, M. J., Lucherini, E., Mayer, J., Chetty, M., & Narayanan, A. (2019). Dark patterns at scale: Findings from a crawl of 11K shopping websites. Proceedings of the ACM on Human-Computer Interaction, 3(CSCW), 1-32."
week_paper_file1 <- "Optional_Reading_Mathur_DarkPatterns.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")
  
```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Shopping online? Find yourself asking: are there really only 3 items left at this price? In some cases, the answer is that it is a downright lie or at best misleading in nature. Yet, it is not always easy to recognize this kind of content or the effect it has on consumers. In the shopping example, consumers may not realize they are being duped into making purchasing decisions they may not have, if fully informed and presented with accurate information. To keep up with this increasing trend towards intentionally misleading user interface choices, or dark patterns, which steer consumers down certain paths for the gain of the service provider, policy-makers are creating, discussing, and reviewing current regulations for online content. In this talk, I present two case studies of misleading online content and the current consumer protections in place to prevent users from being harmed in the US: disguised advertisements and dark patterns used in shopping websites. I will provide evidence about the prevalence of these issues on the web, how users perceive them, and discuss what kinds of solutions can be put into place to help consumers become aware of and be protected from unfair and unjust practices that rely on misleading premises. To conclude, I will provide suggestions for future work for researchers, policy-makers, and designers who are invested in enhancing online consumer protections.



</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:00am-12:20pm </h4>

<br><br>

<p class=footertext2>

**Marshini Chetty** is an assistant professor in the Department of Computer Science at the University of Chicago where she directs the Amyoli Internet Research Laboratory (AIR lab). She specializes in human-computer interaction, usable privacy and security, and ubiquitous computing. Her work has won best paper awards at SOUPS, CHI, and CSCW, and she was a co-recipient of the Annual Privacy Papers for Policymakers award. Her research has been featured in the NYTimes, CNN, Washington Journal, BBC, Chicago Tribune, The Guardian, WIRED, and Slashdot. She has received generous funding from the National Science Foundation, through grants and a CAREER award, as well as the National Security Agency, Facebook, and multiple Google Faculty Research Awards.


</p>

<br>

<p class=footertext2>

**Attendance**: The talk will be held in Rm 295 of 1155 East 60th St. MACSS students who have a last name starting with M through Z (Group 2) are required to attend this week's talk in person. All MACSS faculty members are also welcome to join the talk in person. The rest of MACSS students (Group 1) and all other attendees will need to join the meeting via Zoom ([link](`r zoom_url`)).

<p class=footertext2>

**Participation**: Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a well-developed group question on the issues <a href= `r issues_url`> page </a> of the <a href="https://github.com/uchicago-computation-workshop"> workshop's public repository.</a>

This week's required reading:

- `r readings0`

And optional reading:

- `r readings1`



<br>

<br><br>

---

<p class=footertext> The 2021-2022 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:00 a.m. to 12:20 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a well-developed group question on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
